#!/bin/bash
source ~/.pirc

picmd="bash -c"
if [ "$PI_SSH_ID" != "" ]; then
    picmd="ssh -t $PI_SSH_ID"
fi

browser="chromium"
if [ "$PI_BROWSER" != "" ]; then
    browser="$PI_BROWSER"
fi

wait=5
if [ "$PI_WAIT_STREAM" != "" ]; then
    wait=$PI_WAIT_STREAM
fi

if [ "$PI_FIFO_PATH" == "" ]; then PI_FIFO_PATH="/tmp/pififo"; fi

$picmd "livestreamer \"$@\" best -np omxplayer"
