#!/bin/bash
source ~/.pirc

picmd="bash"
if [ "$PI_SSH_ID" != "" ]; then
    picmd="ssh -t $PI_SSH_ID"
fi

if [ "$PI_SUB_PATH" == "" ]; then PI_SUB_PATH="/tmp/pisubs"; fi

$picmd pkill -9 omxplayer &

$picmd mkdir -p $PI_SUB_PATH &
function dl {
    echo "finding subs..."
    subs=$(jshon -e subtitles -e en <<< $js)
    sub=""
    subopt=""
    if [ "$subs" == "" ]; then
        subs=$(jshon -e automatic_captions -e en <<< $js)
    fi
    if [ "$subs" == "" ]; then
        echo "no subs."
    else
        j=0
        len=$(jshon -l <<< $subs)
        while [ "$len" != "" -a $j -lt $len ]; do
            if [ "$(jshon -e $j -e ext <<<  $subs)" == "\"srt\"" ]; then
                sub="$(jshon -e $j -e url <<< $subs | sed 's/^"\|"$//g' | sed 's/\\\//\//g')"
                break
            fi
            j=$((j+1))
        done
        if [ "$sub" == "" ]; then echo "no sub"
        else
            echo "downloading subs."
            $picmd curl \"$sub\" \> $PI_SUB_PATH/$id.srt
            subopt="--subtitles $PI_SUB_PATH/$id.srt"
        fi
    fi

    echo "finding format..."
    id=$(jshon -e id <<< $js | tr -d \")
    fmts=$(jshon -e formats <<< $js)
    url=""
    ourl=""
    k=0
    len=$(jshon -l <<< $fmts)
    while [ "$len" != "" -a $k -lt $len ]; do
        url=$(jshon -e $k -e url <<< $fmts)
        if [ "$(jshon -e $k -e ext <<< $fmts)" == '"mp4"' ]; then
            ourl=$url
        fi
        k=$((k+1))
    done
    if [ "$PI_PREFER_MP4" = true -a "$ourl" != "" ]; then url=$ourl; fi
    url="$(echo "$url" | sed -E 's/^"|"$//g' | sed -E 's/\\\//\//g')"
    url="$(echo "$url" | sed 's/^"\|"$//g'
    echo "found format."

    $picmd omxplayer -b \"$url\" $subopt
}

echo "determining if video is a playlist..."
js=$(youtube-dl --flat-playlist --youtube-skip-dash-manifest --write-sub --write-auto-sub -J $@)

p="$(jshon -e entries <<< $js)"
if [ "$p" == "" ]; then
    echo "video is not a playlist."
    dl
else
    echo  "video is a playlist."
    i=0
    while [ "$(jshon -e $i <<< $p)" != "" ]; do
        echo "streaming video index $i"
        js=$(youtube-dl --youtube-skip-dash-manifest --write-sub --write-auto-sub --playlist-items $i -J $@ | jshon -e entries -e 0)
        dl
        i=$((i+1))
    done
fi
